### PR TITLE
Merge contents of `rover` repo into `red-bank` repo

### PR DESCRIPTION
**Pull request by larry0x**
Commands I used to prepare this PR:

```bash
git clone https://github.com/mars-protocol/red-bank.git
git clone https://github.com/mars-protocol/rover.git
cd red-bank
git checkout -b merge
git remote add rover ../rover
git fetch rover master
git merge rover/master --allow-unrelated-histories
# have fun resolving conflicts...
```

I don't have a good idea how to merge the deployment scripts. For now I simply rename the files (e.g. `deploy.ts` in the Rover repo is now `deploy.rover.ts`)

### CODE REVIEW

**Comment by larry0x** [comment]
Getting "No space left on device" error for coverage

**Comment by markonmars** [comment]
It might be unnecessary to merge the rover and redbank deploy scripts together into one, but we could unify them somehow so that we can deploy everything with on command.

**Comment by piobab** [comment]
> Getting "No space left on device" error for coverage

We have two options:
1) something similar to this https://github.com/mars-protocol/red-bank/pull/305
2) bump worker disk space

We already decided to go with option 1) for red-bank so maybe we should do it for whole repo the same way, thoughts @larry0x @dancreee ?

**Comment by piobab** [comment]
PR is difficult to review :D so better to check diff between rover repo latest commit (https://github.com/mars-protocol/rover/commit/1176c732a9f1a6c9bc6d97e9fa98c63b2cfe3307) and current branch commit https://github.com/mars-protocol/red-bank/pull/335/commits/bebf5ccc7f29da090934cd771efd2f762f39b6f6

No differences, LGTM!
diff_outposts_and_rover_repos

**Comment by dancreee** [comment]
> > Getting "No space left on device" error for coverage
> 
> We have two options:
> 
> 1. something similar to this [Enable test coverage #305](https://github.com/mars-protocol/red-bank/pull/305)
> 2. bump worker disk space
> 
> We already decided to go with option 1) for red-bank so maybe we should do it for whole repo the same way, thoughts @larry0x @dancreee ?

agree if it's practical to do this

**Comment by piobab** [comment]
All tests passed for me locally, except for:
```
failures:
    redbank_quering_oracle_successfully
    redbank_should_fail_if_no_price
```
It is related to `libraries` feature flag enabled for params contract
```
thread 'redbank_should_fail_if_no_price' panicked at 'called `Result::unwrap()` on an `Err` value: ExecuteError { msg: "failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: \"instantiate\". Exports required by VM: [\"allocate\", \"deallocate\", \"instantiate\"].: create wasm contract failed" }', integration-tests/tests/helpers.rs:149:69
```

Once we extract msgs to types we can remove feature flag and tests should pass.

Moreover we are going to solve `no space error` by reorganization of tests in separate PR (@larry0x pointed to https://github.com/confio/poe-contracts/tree/main/contracts/tgrade-valset/src and it could make sense).

**Comment by piobab** [comment]
@dancreee we agree with @larry0x to merge this PR and fix the rest in separate smaller PRs.

**Pull request merged**
